language: python
python:
- '3.6'
cache: pip
install:
- pip install tox-travis coveralls
script:
- tox
deploy:
  provider: pypi
  skip_cleanup: true
  distributions: bdist_wheel
  user: "__token__"
  password:
    secure: "GkU2xvyjnzuk4HSrlWCc1jfUtzaLVyKrZBV+NxgA9lluximkE5Qa72XVyejcd8gE6tClR8rtHY+bGvD5f0XF7xy4ySIU2yuoFgM7hlQZAhqYcMdNisIpjjpfuJUgZeYeXNlMUquTeyQUYJnFybcVHaZqKZYhnco6pVHLWKk+KAyjpwABvDUgMHaGkJhWhrD0HY24Ods2hB9DmekxwS5KbJlW7qR9UBRDvW/8JxhxEaLsDeXOPil4dwdf4Rae48wxVHofYos98b9/Xo18yf9ptC7ve6Wc6mIWbdY7OjyLdj9PX+1f2J2EKkajjlFS2Ir7W/vGHzLg5QGLAeBIY0DBo9f1ytcyNtsyniO+gDgE5+5bq7ERKk68iTjxgjYRTkJ3ear8BNnEzUG3hx6F3ffGW6oauXY2RAwRMhOfBqIfpFQV8IKUVzuA1XHft1momOiauRKFwTVlQ+8a+0gYCXXa9/85Gxur/8/JpLOTe152EgjarGRP/Vm7R3/I2kUuqUyzbJrwIqUmx3CimcvqPoS/gjdKqRuAeFU93nXmPCxmVe0soSzIdTDqsUA2QPbpBX4zTLrhCXf/EIJWM/3E4AdrvnZusnZaFBrENQ8QFnwgSsGoSr9NvGRc5fzXd84FxWyjTWJlFV1C1T8+RJ9h818w4ChApHXZrmkaxaG7OwO0Sf0="
  on:
    branch: master
  skip_existing: true
after_success:
- coveralls --verbose
before_install:
- openssl aes-256-cbc -K $encrypted_ef0e98cf6d8a_key -iv $encrypted_ef0e98cf6d8a_iv
  -in sec.tar.xz.enc -out sec.tar.xz -d
- tar xvf sec.tar.xz